import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const contentRoot = path.join(root, "content");
const outputPath = path.join(root, "src", "content.generated.ts");

async function readMarkdownDirectory(directory, kind) {
  const entries = await fs.readdir(directory, { withFileTypes: true }).catch(() => []);
  const files = entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".md"))
    .map((entry) => entry.name)
    .sort();
  return Promise.all(files.map((filename) => parseMarkdown(path.join(directory, filename), kind)));
}

function parseValue(value) {
  const trimmed = value.trim();
  if (trimmed.startsWith("[")) {
    try {
      return JSON.parse(trimmed);
    } catch {
      return trimmed
        .slice(1, -1)
        .split(",")
        .map((item) => item.trim())
        .filter(Boolean);
    }
  }
  if (trimmed.startsWith("{")) return JSON.parse(trimmed);
  if (trimmed === "true") return true;
  if (trimmed === "false") return false;
  if (trimmed === "null") return null;
  if (/^-?\d+(\.\d+)?$/.test(trimmed)) return Number(trimmed);
  if (
    (trimmed.startsWith('"') && trimmed.endsWith('"')) ||
    (trimmed.startsWith("'") && trimmed.endsWith("'"))
  ) {
    return trimmed.slice(1, -1);
  }
  return trimmed;
}

async function parseMarkdown(filename, kind) {
  const source = await fs.readFile(filename, "utf8");
  const match = source.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!match) throw new Error(`${filename} is missing YAML front matter.`);

  const frontMatter = {};
  for (const line of match[1].split(/\r?\n/)) {
    if (!line.trim() || line.trim().startsWith("#")) continue;
    const separator = line.indexOf(":");
    if (separator < 1) throw new Error(`Invalid front matter in ${filename}: ${line}`);
    frontMatter[line.slice(0, separator).trim()] = parseValue(line.slice(separator + 1));
  }

  const slug = String(frontMatter.slug || path.basename(filename, ".md"));
  const timestamp = String(frontMatter.published_at || "2026-08-29T00:00:00.000Z");
  return {
    ...frontMatter,
    id: `file-${kind}-${slug}`,
    slug,
    body: match[2].trim(),
    created_at: timestamp,
    updated_at: timestamp,
    published: frontMatter.published !== false,
    ...(kind === "entry"
      ? { published_at: frontMatter.published === false ? null : timestamp }
      : {}),
  };
}

const domains = await readMarkdownDirectory(path.join(contentRoot, "domains"), "domain");
const projects = await readMarkdownDirectory(path.join(contentRoot, "projects"), "project");
const entries = await readMarkdownDirectory(path.join(contentRoot, "log"), "entry");
const settings = JSON.parse(await fs.readFile(path.join(contentRoot, "settings.json"), "utf8"));
const tags = JSON.parse(await fs.readFile(path.join(contentRoot, "tags.json"), "utf8").catch(() => "[]"));
const projectIds = new Map(projects.map((project) => [project.slug, project.id]));

for (const entry of entries) {
  if (entry.project) entry.project_id = projectIds.get(entry.project) ?? null;
  delete entry.project;
}

const contentJson = JSON.stringify({ settings, domains, tags, projects, entries }, null, 2)
  .replace('"domains": []', '"domains": [] as Array<Record<string, any>>');
const output = `// Generated by scripts/generate-content.mjs. Do not edit directly.\nexport const fileContent = ${contentJson};\n`;
await fs.writeFile(outputPath, output);
console.log(
  `Generated file content: ${domains.length} domains, ${projects.length} projects, ${entries.length} entries.`,
);
